### ISSUE TITLE
mwn.init - defaultParams.assert overrides maxRetries and crashes on encountering maxlag

### ISSUE THREAD

**Issue by Ivi104** [siddharthvp/mwn#86]
Steps to reproduce:
* Initialize the bot with mwn.init, and use a BotPassword 
* add `defaultParams: { assert: 'user' }` (as described in [mwn.readthedocs.io](https://mwn.readthedocs.io/en/stable/index.html)
* attempt to login with `client.getSiteInfo()`
* The wiki sends a high maxlag value
 
Current behavior:
* the bot attempt to login, receive maxlag, wait 5 seconds, assertUser will fail, and it will try to login again.
* This cycle will continue infinitely (ignoring maxRetries), until maxlag clears and the bot manages to login, at which point it will crash with message "already logged in".

Expected behavior:
* it should respect maxRetries, and attempt to login only 3 times by default.
* assertuserfailed should not reset the maxRetries counter
* When maxlag clears it should not crash after successfully logging in.

See log below:

Encountered maxlag: 9.437752 seconds lagged. Waiting for 5 seconds before retrying
[2024-12-04 21:10:08] [W] Received assertuserfailed, attempting to log in and retry
[2024-12-04 21:10:08] [W] Encountered maxlag: 12.360417 seconds lagged. Waiting for 5 seconds before retrying
[2024-12-04 21:10:13] [W] Received assertuserfailed, attempting to log in and retry
[2024-12-04 21:10:13] [W] Encountered maxlag: 10.485554 seconds lagged. Waiting for 5 seconds before retrying
[2024-12-04 21:10:18] [W] Received assertuserfailed, attempting to log in and retry
[2024-12-04 21:10:18] [W] Encountered maxlag: 9.296703 seconds lagged. Waiting for 5 seconds before retrying
[2024-12-04 21:10:23] [W] Received assertuserfailed, attempting to log in and retry
[2024-12-04 21:10:25] [S] [mwn] Login successful: [REDACTED]
/data/project/hrwp/www/js/node_modules/mwn/build/error.js:43
    return Promise.reject(new MwnError(errorConfig));
                          ^

MwnError: Already logged in as [REDACTED], logout first to re-login
    at Object.rejectWithError (/data/project/hrwp/www/js/node_modules/mwn/build/error.js:43:27)
    at mwn.login (/data/project/hrwp/www/js/node_modules/mwn/build/bot.js:443:24)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Response.process ([REDACTED]/node_modules/mwn/build/core.js:185:17)
    at async Response.process ([REDACTED]/node_modules/mwn/build/core.js:185:17)
    at async mwn.login ([REDACTED]/node_modules/mwn/build/bot.js:388:36)
    at async Response.process ([REDACTED]/node_modules/mwn/build/core.js:185:17)
    at async Response.process ([REDACTED]/node_modules/mwn/build/core.js:185:17)
    at async mwn.login ([REDACTED]/node_modules/mwn/build/bot.js:388:36) {
  code: 'mwn_failedlogin',
  info: 'Already logged in as IviBot@Toolforge, logout first to re-login',
  response: {
    login: {
      result: 'Aborted',
      reason: 'Cannot log in when using MediaWiki\\Session\\BotPasswordSessionProvider sessions.'
    }
  }
}

**Comment by siddharthvp** [comment]
The behaviour appears to have changed with https://github.com/siddharthvp/mwn/commit/54d0eae7ded8dc5e60eb947e1e5ee8ecfe227c0a. It now gets stuck in an deadlock (since the internally invoked login() call simply waits for the first login() to finish, which doesn't finish until the second call finishes) instead of recursing infinitely. I think the most suitable solution is to just ignore maxlag for login and token-related requests. It isn't required anyway as these calls don't write to the db.
